forbidden_words = [
    # Kata-kata terkait aktivitas seksual
    "bokep", "ngewe", "ngentot", "ngesex", "ngeseks", "bersetubuh", "persetubuhan", "berzina", "perzinaan",
    "cumbu", "bercumbu", "oral", "anal", "masturbasi", "onani", "coli", "colmek", "sange", "sagne",
    "desah", "mendesis", "ejakulasi", "sperma", "mani", "lendir", "basah", "kelamin", "vagina", "penis",
    "kontol", "memek", "pepek", "tempik", "itil", "toket", "tobrut", "pentil", "jembut", "puki", "pukimak",
    "picek", "ngaceng", "horny", "nafsu", "birahi", "rangsang", "terangsang", "orgasme", "klimaks",
    "asu", "anjing", "bajingan", "brengsek", "jancok", "bangsat", "keparat", "bedebah", "berengsek",
    "setan", "syaitan", "iblis", "laknat", "terkutuk", "sialan", "sial", "kampret", "goblok", "tolol",
    "idiot", "bego", "dungu", "bebal", "bodoh", "cacat", "cacat_mental", "sampah", "kotoran", "najis",
    "butut", "jorok", "buruk", "jelek", "buruk_rupa", "pecundang", "penipu", "penjahat", "maling",
    "begundal", "preman", "berandal", "bandit", "bajingan_tengik", "monyet", "babi", "onta", "udik",
    "ndeso", "gaptek", "kamseupay", "alay", "tai",
    "pelacur", "sundal", "sundel", "pelacuran", "prostitusi", "porno", "pornografi", "cabul", "hidung_belang",
    "main_belakang", "balapan_liar", "film_biru", "adegan_ranjang", "esek_esek", "lendir",
    "judi", "judi_online", "online_casino", "taruhan", "slot", "roulette", "poker", "sabung_ayam",
    "betting", "togel", "bandar_togel", "pasang_taruhan", "jackpot", "win_big", "gambling", "kartu_remi",
    "poker_online", "poker_uang_asli", "uang_taruhan", "deposit_judi", "domino_qq", "dadu_online",
    "pemain_judi", "online_betting", "live_casino", "betting_site", "casino_online", "tangkasnet",
    "penipu_judi", "kredit_pinjol", "pinjaman_online", "pinjol_ilegal", "bunga_pinjaman", "pinjaman_tanpa_agunan",
    "bunga_tinggi", "penipuan_pinjaman", "utang_cepat", "pinjaman_instan", "tanya_pinjol",
    "pinjaman_segera_cair", "cair_tanpa_syarat", "pinjaman_cepat", "pinjaman_pribadi", "utang_online",
    "cair_cepat", "pendanaan_online", "pinjaman_uang_cepat", "pinjol_resmi", "pinjaman_ilegal",
    "narkoba", "narkotik", "obat_terlarang", "ganja", "sabu", "ekstasi", "heroin", "kokain", "morfin",
    "putau", "pil_koplo", "brengsek", "bangsat", "kurang_ajar", "biadab", "terkutuk", "terlaknat", "penghianat",
     "perusak", "penghancur", "perusak_dunia", "pengacau", "penyimpangan",
    "keji", "jahat", "jahat_sekali", "kejam", "kekerasan", "pemerkosaan",
    "pencurian", "perampokan", "penyerangan", "permusuhan", "konflik", "pertengkaran",
    "perkelahian", "pertempuran", "peperangan", "kekacauan", "kerusakan",
    "kecelakaan", "musibah", "bencana", "tragedi", "kematian", "pembunuhan",
    "bunuh_diri", "pembunuh", "pembantaian", "penyiksaan", "penyiksaan_kejam",
    "teroris", "terorisme", "radikal", "radikalisme", "ekstrimis", "ekstrimisme",
    "komplotan", "komplotan_kejam", "tindakan_kejam", "jebakan", "jebak",
    "tipu", "tukang_tipu", "penipuan", "kecurangan", "pembohong", "kebohongan",
    "mencuri", "rampas", "perampas", "perampasan", "maling",
    "stres", "stres_berat", "tekanan_mental", "depresi", "kecemasan",
    "gila", "gila_gilaan", "sinting", "edan", "sarap", "gendeng",
    "abnormal", "kelainan", "penyakit_mental", "gangguan_jiwa",
    "haram", "maksiat", "dosa", "nista", "menista", "penistaan",
    "zalim", "aniaya", "menganiaya", "penindasan", "penyiksaan",
    "mencurigakan", "berbahaya", "mengancam", "ancaman", "mengintimidasi",
    "permainan", "permainan_kotor", "licik", "curang", "muslihat",
    "feodal", "kolot", "terbelakang", "primitif", "kuno", "tradisional",
    "bebal", "bodoh", "dungu", "tolol", "idiot", "goblok", "otak_udang",
    "pecundang", "kalah", "kekalahan", "gagal", "kegagalan", "putus_asa",
    "parasit", "benalu", "pengganggu", "perusak", "penghancur",
    "hidung_belang", "playboy", "mata_keranjang", "genit", "cabul",
    "pukimak", "puki", "kontol", "memek", "pepek", "tempik",
    "gerandong", "basah", "celana_dalam", "blonjo", "penjara",
    "terjebak", "lapar", "balapan_liar", "jongkok", "ambruk",
    "nahan", "guling", "hancur", "lempar", "gebuk", "rebutan", "lepas",
    "kacau", "kambing", "hidung_keriput", "buaya_darat", "jengkol",
    "gulat", "main_belakang", "garuk", "colmek", "binal",
    "kolam", "panjat", "narkotika", "minuman_keras", "tutup_mulut", "masalah",
    "teriak", "ajak_ajakan", "buang", "penghancur", "beruk", "babi_ngepet",
    "tersembunyi", "orang_bodoh", "gerombolan", "bengkok", "kehilangan",
    "ngaco", "dilarang", "buruh", "banjir", "badut", "sembunyi", "robek",
    "debu", "cabut", "kolam_renang", "kurang_ajar", "biadab", "terkutuk", "terlaknat", "penghianat", "perusak", "penghancur", "perusak_dunia",
    "pengacau", "penyimpangan", "keji", "jahat", "jahat_sekali", "kejam", "kekerasan", "pemerkosaan",
    "pencurian", "perampokan", "penyerangan", "permusuhan", "konflik", "pertengkaran", "perkelahian",
    "pertempuran", "peperangan", "kekacauan", "kerusakan", "kecelakaan", "musibah", "bencana", "tragedi",
    "kematian", "pembunuhan", "bunuh_diri", "pembunuh", "pembantaian", "penyiksaan", "penyiksaan_kejam",
    "teroris", "terorisme", "radikal", "radikalisme", "ekstrimis", "ekstrimisme", "komplotan",
    "komplotan_kejam", "tindakan_kejam", "jebakan", "jebak", "tipu", "tukang_tipu", "penipuan",
    "kecurangan", "pembohong", "kebohongan", "mencuri", "rampas", "perampas", "perampasan",
    "stres", "stres_berat", "tekanan_mental", "depresi", "kecemasan", "gila", "gila_gilaan", "sinting",
    "edan", "sarap", "gendeng", "abnormal", "kelainan", "penyakit_mental", "gangguan_jiwa", "haram",
    "maksiat", "dosa", "nista", "menista", "penistaan", "zalim", "aniaya", "menganiaya", "penindasan",
    "mencurigakan", "berbahaya", "mengancam", "ancaman", "mengintimidasi", "permainan", "permainan_kotor",
    "licik", "curang", "muslihat", "feodal", "kolot", "terbelakang", "primitif", "kuno", "tradisional",
    "otak_udang", "kalah", "kekalahan", "gagal", "kegagalan", "putus_asa", "benalu", "pengganggu",
    "playboy", "mata_keranjang", "lendir", "gerandong", "celana_dalam", "blonjo", "penjara", "terjebak",
    "lapar", "jongkok", "ambruk", "nahan", "guling", "hancur", "lempar", "gebuk", "rebutan", "lepas",
    "kacau", "kambing", "hidung_keriput", "buaya_darat", "jengkol", "gulat", "main_belakang", "garuk",
    "binal", "kolam", "panjat", "minuman_keras", "tutup_mulut", "masalah", "teriak", "ajak_ajakan",
    "buang", "beruk", "babi_ngepet", "tersembunyi", "gerombolan", "bengkok", "kehilangan", "ngaco",
    "dilarang", "buruh", "banjir", "badut", "sembunyi", "robek", "debu", "cabut", "kolam_renang",
    "padam", "tercecer", "pecat", "mengecewakan", "hakim", "tersangka", "benar_benar_rusak", "guncangan",
    "masalah_sosial", "teman_palsu", "sekolah_gelap", "penyalahgunaan", "masalah_berat",
    "sama_sama_cacat", "tega", "berdarah", "lawan", "penjahat_dunia", "terselubung", "pukul",
    "lempar_batu", "tangkap", "bulutangkis", "jelek", "ngatuk", "kenalan_buruk", "melekat", "serangan",
    "pelabuhan", "bersentuhan", "tumbuh", "melarikan_diri", "kirim", "kabur_lagi", "ramuan",
    "pentil", "toket", "tobrut", "sagne", "harem", "cok", "gacor", "maxwin", "win_uang", "bonus_taruhan",
    "judi_haram", "pinjaman_bunga_tinggi", "pinjaman_jangka_pendek", "utang_berbunga_tinggi",
    "aplikasi_judi", "pinjaman_tanpa_jaminan", "pembusukan", "liar", "penyimpangan",
    "orang_bodoh", "buruk", "narkotika", "kotor", "gelap", "perusakan", "mencuri",
    "terkutuk", "buruk_rupa", "stres_berat", "kelainan", "permainan_kotor",
    "komplotan_kejam", "tindakan_kejam", "perusak_dunia", "obat_terlarang", "terselubung", "kerusakan",
    "kenalan_buruk", "melekat", "melarikan_diri", "kabur_lagi", "ramuan", "tersembunyi", "orang_bodoh",
    "gerombolan", "bengkok", "kehilangan", "ngaco", "dilarang", "buruh", "banjir", "badut", "sembunyi",
    "robek", "debu", "cabut", "kolam_renang", "padam", "tercecer", "pecat", "mengecewakan", "hakim",
    "tersangka", "benar_benar_rusak", "guncangan", "masalah_sosial", "teman_palsu", "sekolah_gelap",
    "penyalahgunaan", "masalah_berat", "sama_sama_cacat", "tega", "berdarah", "lawan", "penjahat_dunia",
    "pukul", "lempar_batu", "tangkap", "bulutangkis", "jelek", "ngatuk", "serangan", "pelabuhan",
    "bersentuhan", "tumbuh", "kirim", "pentil", "toket", "tobrut", "sagne", "harem", "cok", "gacor",
    "maxwin", "win_uang", "bonus_taruhan", "judi_haram", "pinjaman_bunga_tinggi", "pinjaman_jangka_pendek",
    "utang_berbunga_tinggi", "aplikasi_judi", "pinjaman_tanpa_jaminan", "pembusukan", "liar",
    "orang_bodoh", "buruk", "narkotika", "kotor", "gelap", "perusakan", "mencuri", "terkutuk",
    "buruk_rupa", "stres_berat", "kelainan", "komplotan_kejam", "tindakan_kejam", "obat_terlarang",
    "terselubung", "kerusakan", "kenalan_buruk", "melekat", "melarikan_diri", "kabur_lagi", "ramuan",
    "tersembunyi", "gerombolan", "bengkok", "kehilangan", "ngaco", "dilarang", "buruh", "banjir",
    "badut", "sembunyi", "robek", "debu", "cabut", "kolam_renang", "padam", "tercecer", "pecat",
    "mengecewakan", "hakim", "tersangka", "benar_benar_rusak", "guncangan", "masalah_sosial",
    "bencong", "waria", "bispak", "lesbi", "homo", "gay", "transgender", "cowo", "cewe", "pacar", "selingkuh",
    "selingkuhan", "kawin", "nikah", "cerai", "janda", "duda", "mertua", "iparmu", "besan", "tetangga",
    "kampung", "kota", "pulau", "negara", "dunia", "akhirat", "surga", "neraka", "malaikat", "setan",
    "jin", "hantu", "iblis", "setan_gundul", "pocong", "kuntilanak", "genderuwo", "tuyul", "babi_ngepet",
    "pesugihan", "santet", "guna-guna", "teluh", "sihir", "mistis", "gaib", "klenik", "tahayul", "mitos",
    "legenda", "dongeng", "cerita", "kisah", "sejarah", "peristiwa", "kejadian", "musibah", "bencana",
    "tragedi", "kematian", "pembunuhan", "bunuh_diri", "pembunuh", "pembantaian", "penyiksaan",
    "penyiksaan_kejam", "teroris", "terorisme", "radikal", "radikalisme", "ekstrimis", "ekstrimisme",
    "komplotan", "komplotan_kejam", "tindakan_kejam", "jebakan", "jebak", "tipu", "tukang_tipu",
    "penipuan", "kecurangan", "pembohong", "kebohongan", "mencuri", "rampas", "perampas", "perampasan",
    "stres", "stres_berat", "tekanan_mental", "depresi", "kecemasan", "gila", "gila_gilaan", "sinting",
    "edan", "sarap", "gendeng", "abnormal", "kelainan", "penyakit_mental", "gangguan_jiwa", "haram",
    "maksiat", "dosa", "nista", "menista", "penistaan", "zalim", "aniaya", "menganiaya", "penindasan",
    "mencurigakan", "berbahaya", "mengancam", "ancaman", "mengintimidasi", "permainan", "permainan_kotor",
    "licik", "curang", "muslihat", "feodal", "kolot", "terbelakang", "primitif", "kuno", "tradisional",
    "otak_udang", "kalah", "kekalahan", "gagal", "kegagalan", "putus_asa", "parasit", "benalu",
    "pengganggu", "playboy", "mata_keranjang", "lendir", "gerandong", "celana_dalam", "blonjo",
    "penjara", "terjebak", "lapar", "jongkok", "ambruk", "nahan", "guling", "hancur", "lempar",
    "gebuk", "rebutan", "lepas", "kacau", "kambing", "hidung_keriput", "buaya_darat", "jengkol",
    "gulat", "main_belakang", "garuk", "binal", "kolam", "panjat", "minuman_keras", "tutup_mulut",
    "masalah", "teriak", "ajak_ajakan", "buang", "beruk", "babi_ngepet", "tersembunyi", "gerombolan",
    "bengkok", "kehilangan", "ngaco", "dilarang", "buruh", "banjir", "badut", "sembunyi", "robek",
    "debu", "cabut", "kolam_renang", "padam", "tercecer", "pecat", "mengecewakan", "hakim", "tersangka",
    "benar_benar_rusak", "guncangan", "masalah_sosial", "teman_palsu", "sekolah_gelap", "penyalahgunaan",
    "masalah_berat", "sama_sama_cacat", "tega", "berdarah", "lawan", "penjahat_dunia", "pukul",
    "lempar_batu", "tangkap", "bulutangkis", "jelek", "ngatuk", "kenalan_buruk", "melekat", "serangan",
    "pelabuhan", "bersentuhan", "tumbuh", "melarikan_diri", "kirim", "kabur_lagi", "ramuan",
    "pentil", "toket", "tobrut", "sagne", "harem", "cok", "gacor", "maxwin", "win_uang", "bonus_taruhan",
    "judi_haram", "pinjaman_bunga_tinggi", "pinjaman_jangka_pendek", "utang_berbunga_tinggi",
    "aplikasi_judi", "pinjaman_tanpa_jaminan", "pembusukan", "liar", "orang_bodoh", "buruk", "narkotika",
    "kotor", "gelap", "perusakan", "mencuri", "terkutuk", "buruk_rupa", "stres_berat", "kelainan",
    "komplotan_kejam", "tindakan_kejam", "obat_terlarang", "terselubung", "kerusakan", "kenalan_buruk",
    "melekat", "melarikan_diri", "kabur_lagi", "ramuan", "tersembunyi", "gerombolan", "bengkok",
    "kehilangan", "ngaco", "dilarang", "buruh", "banjir", "badut", "sembunyi", "robek", "debu",
    "cabut", "kolam_renang", "padam", "tercecer", "pecat", "mengecewakan", "hakim", "tersangka",
    "benar_benar_rusak", "guncangan", "masalah_sosial", "teman_palsu", "sekolah_gelap", "penyalahgunaan",
    "masalah_berat", "sama_sama_cacat", "tega", "berdarah", "lawan", "penjahat_dunia", "pukul",
    "lempar_batu", "tangkap", "bulutangkis", "jelek", "ngatuk", "serangan", "pelabuhan", "bersentuhan",
    "tumbuh", "kirim", "sange", "sagne", "itil", "toket", "tobrut", "pentil", "jembut", "puki", "pukimak",
    "picek", "ngaceng", "horny", "nafsu", "birahi", "rangsang", "terangsang", "orgasme", "klimaks",
    "lendir", "gerandong", "celana_dalam", "blonjo", "penjara", "terjebak", "lapar", "jongkok", "ambruk",
    "nahan", "guling", "hancur", "lempar", "gebuk", "rebutan", "lepas", "kacau", "kambing", "hidung_keriput",
    "buaya_darat", "jengkol", "gulat", "main_belakang", "garuk", "binal", "kolam", "panjat", "minuman_keras",
    "tutup_mulut", "masalah", "teriak", "ajak_ajakan", "buang", "beruk", "babi_ngepet", "tersembunyi",
    "gerombolan", "bengkok", "kehilangan", "ngaco", "dilarang", "buruh", "banjir", "badut", "sembunyi",
    "robek", "debu", "cabut", "kolam_renang", "padam", "tercecer", "pecat", "mengecewakan", "hakim"
]